### ISSUE TITLE
Match request body for PUT and POST requests

### ISSUE THREAD

**Issue by just-boris** [ctimmerm/axios-mock-adapter#10]
Hello! 

I started to use this library since I switched my work from Angular to React and axios for http-requests. Thank you for this package, that was really a missing feature.

Now I have a lack of matching body for requests with payload. I'd like to do something like this:

```js
mock.onPost('/api/users', {name: 'new user', email: 'test@email.com'}).reply(200);
```

Then I can to test not only that request was actually called, but also that it has proper body. That feature was built-in in Angular's mock library, so it would be nice to have it there as well.

**Comment by ludovicthomas** [comment]
You can use the 'function' as a reply argument instead of 200.

Something like:
```
mock. onPost('/api/users').reply(function(config) {
   if (config.data.name === 'new user' && config.data.email === 'test@email.com'){
      return [200, 'OK'];
   }
  return [404, 'Invalid'];
});
```

**Comment by just-boris** [comment]
Well, this is how I worked around this now.

But the thing is that it is very popular use-case, but now it requires so much boilerplate code. It would be nice to have a shortcut for this.

**Comment by wirmar** [comment]
I can try and write a PR for this if wanted.
@ctimmerm are you okay with having a dependency for a deep equal library like https://github.com/chaijs/deep-eql to implement this Feature or is there an easier way?

**Comment by ctimmerm** [comment]
Yep, sounds good to me.

**Comment by snowffer** [comment]
@ludovicthomas Still doesn't work for me. Return 404.
