### ISSUE TITLE
 handler not found question

### ISSUE THREAD

**Issue by annilq** [ctimmerm/axios-mock-adapter#105]
Hi,I found a question ,in my project, the backend has provided  some api to me , so I just want to adapt some unprovided Api ,but when I send a request exsited and  I get a " 404" error,and I found the code in the <code>handle_request.js</code> below just throw a 404 error
```
    utils.settle(resolve, reject, {
      status: 404,
      config: config
    }, mockAdapter.delayResponse);

```
and I wonder why not just send a original request like that?
```
    config.adapter = mockAdapter.originalAdapter;
    mockAdapter
      .axiosInstance
      .request(config)
      .then(resolve, reject);
```
or how can I solve my problem in another way?
at last,expecting your reply and thanks for the wanderful library

**Comment by ctimmerm** [comment]
I'm not entirely sure what you're trying to do. Do you want to mock a request, then send a request to the server and use the response to create the data for the response of the mocked request?

**Comment by annilq** [comment]
I just want to mock the request that the backend doesn't provide,I don't want to mock every request,and I only create a single mock instance to handle all axios instance,so when I send a exsited request I want the mock doesn't handle it,just throw it to the originalAdapter,maybe I can use the <code>passThrough</code>method for the provied api?

**Comment by ctimmerm** [comment]
Yeah, this case is described in the readme:

```js
// Mock specific requests, but let unmatched ones through
mock
  .onGet('/foo').reply(200)
  .onPut('/bar', { xyz: 'abc' }).reply(204)
  .onAny().passThrough();
```
