### ISSUE TITLE
typescript definition file for axios-mock-adapter

### ISSUE THREAD

**Issue by goodwillguy** [ctimmerm/axios-mock-adapter#11]
Should have typescript definition files in the repository

**Comment by andrepinguim** [comment]
I'll try to do this.

**Comment by testerez** [comment]
Would be appreciated ;)

**Comment by leosilva1243** [comment]
@andrepinguim still trying?

**Comment by andrepinguim** [comment]
I'm busy a lot with other projects. I made a draft from an older version of axios-mock-adapter and do not ran any test, so any help will be appreciated!

**Comment by tkryskiewicz** [comment]
Hi, I have submitted #76 today. Any comments/suggestions are welcome.

**Comment by tkryskiewicz** [comment]
Hey, 

Those definitions got merged into DefinitelyTyped. Once they're merged to axios-mock-adapter, I'll remove them from DT.

**Comment by zachrip** [comment]
@tkryskiewicz I don't like having to use cjs require on the import. I'm going to put in a PR to allow default imports: `import AxiosMockAdapter from 'axios-mock-adapter;` - would love your help to update the typings if it goes in.

**Comment by tkryskiewicz** [comment]
@zachrip both kinds of export (export assignment and default export) can't be used together, so I'll probably change this to be default export, because it allows to export additional types.
