### ISSUE TITLE
onGet returns 404 for specified params

### ISSUE THREAD

**Issue by jannakha** [ctimmerm/axios-mock-adapter#112]
chaining onGet with same url returns 404 for all queries except last one, eg sample code will return results for 'Jane' but will return 404 for 'John' or 'Jack'

```
mock
.onGet('/users', { params: { searchText: 'John' } })
.reply(200, {users: [{ id: 1, name: 'John Smith' }]})
.onGet('/users', { params: { searchText: 'Jack' } })
.reply(200, {users: [{ id: 1, name: 'Jack Smith' }]})
.onGet('/users', { params: { searchText: 'Jane' } })
.reply(200, {users: [{ id: 1, name: 'Jane Smith' }]});
```

introduced in the latest version (v.1.10 was fine)

**Comment by ctimmerm** [comment]
Yep, I noticed it as well, I'll fix it asap.

**Comment by franciscop-invast** [comment]
To fix it and retrieve the original intention of the PR you could do this inside utils.js:

```js
function find(array, predicate) {
  var good = array.filter(function (value) {
    return predicate(value);
  });
  return good[good.length - 1];
}
```

Instead of the original:

```js
function find(array, predicate) {
  var length = array.length;
  for (var i = 0; i < length; i++) {
    var value = array[i];
    if (predicate(value)) return value;
  }
}
```

(And also revert the original PR since this takes care of it)

**Comment by franciscop-invast** [comment]
Or, just occurred to me an even better way, flip the array around and return the first match so you don't have to loop through them all:

```js
function find(array, predicate) {
  var length = array.length;
  for (var i = length - 1; i >= 0; i--) {
    var value = array[i];
    if (predicate(value)) return value;
  }
}
```

**Comment by ctimmerm** [comment]
I'll do a patch release first to get back to a working version. Making the change in `find` is not a complete solution since it does not take care of `replyOnce` handlers.

**Comment by ctimmerm** [comment]
I've published v1.13.1 which reverts the broken functionality.

**Comment by franciscop-invast** [comment]
Thank you for the really quick response 💓

**Comment by davidlewallen** [comment]
Im reworking PR #109 as I didnt take in account for params. My current branch has test verifying that the changes Ive made on overwriting existing mocks does not affect mocks with same paths but different params and headers. Is there anything else I should be aware of? Im also having issues with chaining test regarding replyOnce
