### ISSUE TITLE
Network Error on All onPost request

### ISSUE THREAD

**Issue by wsmith-3** [ctimmerm/axios-mock-adapter#127]
Axios mock adapter works great with all of my get request, but for all of my post request I'm getting a network error.  I've tried adding a function in the reply to check config.data and I've tried not sending any params with the request. I'm not sure what I'm doing wrong with the onPost method but all of them return Network Error. Here's the code.
`import axios from 'axios'

export const PostActivation = (info) => {
	let token = localStorage.getItem('jwt')
	return axios.post(process.env.REACT_APP_API_URL + '/users/add/activation',{
		headers: {
			Authorization: `Bearer ${token}`
		},
		email: info.activateEmail,
		tridentNumber: info.activateTrident,
		code: info.code
	})
	.then(response => {
		// console.log(response)
		return response.data
	})
	.catch(err => {
		// console.log(err.message)
		throw new Error(err.message)
	})
}` 
and the test code is 

`import React from 'react'
import MockAdapter from 'axios-mock-adapter'
import { PostActivation } from './postActivation'

const mock = new MockAdapter()

beforeEach(()=> {
	mock.reset()
})

test('valid postActivation request', () => {
	let response = {
		data:'success'
	}
	mock.onPost(process.env.REACT_APP_API_URL + '/users/add/activation', {
		email:'test@test.com',
		tridentNumber:'2422',
		code:'1234'
	}).reply(200, {response})
	let info = {
		activateEmail:'test@test.com',
		activateTrident:'2422',
		code:'1234'
	}
	PostActivation(info)
	.then(res => {
		console.log(response)
	})
	.catch(err => {
		console.log(err)
	})
})`

any help would be greatly appreciated.

**Comment by abhijeetahuja** [comment]
What was the issue?

**Comment by mehafi** [comment]
I have the same issue.
How it was resolved?
