### ISSUE TITLE
Match data and params in `onPut`, `onPost`

### ISSUE THREAD

**Issue by thk2b** [ctimmerm/axios-mock-adapter#129]
I would like to match specific data and params in an `onPut` handler.

The docs mention this:

> Mocking a request with a specific request body/data
> `mock.onPut('/product', { id: 4, name: 'foo' }).reply(204);`

> Mocking a GET request with specific parameters
> `mock.onGet('/users', { params: { searchText: 'John' } }).reply(200, {...})`

So, it's possible to match params for `get` requests, and data for `put` and `post`. But [this](https://github.com/ctimmerm/axios-mock-adapter/blob/9a29ced338494db577236248ed9f50afdad2c722/test/basics.spec.js#L129) test case shows that it's not possible to match params in `onPut`.
```js
  it("can't pass query params for put to match to a handler", function() {
    mock.onPut('/withParams', { params: { foo: 'bar', bar: 'foo' } }).reply(200);

    return instance
      .put('/withParams', { params: { bar: 'foo', foo: 'bar' }, in: true })
      .catch(function(error) {
        expect(error.response.status).to.equal(404);
      });
  });
```

Specifically, something like this would be convenient:
`mock.onPut('/users', { params: { userId: '123' }, data: { userName: 'new userName' }})`,
or
`mock.onPut('/users', { userName: 'new userName' }, { userId: '123' })`

I achieved something equivalent with `mock.onAny().reply()`, which works well with jest.
```js
const newProfile = {
     name: 'new name'
}

mock.onAny().reply( config => {
    try {
        expect(config.url).toBe('/profile')
        expect(config.method).toBe('put')
        expect(config.params).toEqual({ id: '123' })
        expect(config.data).toEqual(JSON.stringify(newProfile))
        return [202, newProfile]    
    } catch (e){
        done.fail(e)
        return [500]
    }

})
```
But this is a bit convoluted, I have to manually check the url, params, parse the data, etc...

Is there a reason why this isn't or can't be implemented ? Otherwise, I'd be happy to work on a solution.

**Comment by thk2b** [comment]
This is similar to #88, possibly a duplicate.

**Comment by ctimmerm** [comment]
PR here: https://github.com/ctimmerm/axios-mock-adapter/pull/130
