### ISSUE TITLE
Breaking changes in axios >= 0.13.0

### ISSUE THREAD

**Issue by wirmar** [ctimmerm/axios-mock-adapter#13]
@mzabriskie already addressed some of those Breaking Changes in #12, but there is also the change that rejected responses should now reject with an error object with the response attached as error.response and not only with the response. See https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#error-handling.

This makes my test fail when updating my code to work with the new axios version.

**Comment by just-boris** [comment]
@ctimmerm do you have any estimation about release?

**Comment by ctimmerm** [comment]
I'll make a release later today. The reason I want to maintain backwards compatibility is that I don't want to force people to update their axios version just to use new features in axios-mock-adapter.

**Comment by wirmar** [comment]
In axios error.response is undefined when no response was received from the server (network error etc). Shouldn't axios-mock-adapter also return error.response undefined when no handler was found?

**Comment by ctimmerm** [comment]
If there's there's no matching handler found the mock adapter returns a 404 response, so error.response should not be undefined.
