### ISSUE TITLE
Unhandled Promise rejections from instanceof check

### ISSUE THREAD

**Issue by metrip** [ctimmerm/axios-mock-adapter#132]
The `handleRequest` function checks for `result.then instanceof Function` to determine if a Promise result is returned from the handler, in https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/handle_request.js#L52

This does not seem to be correct, as this is not true for returned rejected promises in all environments; in my case Node.js 8.10. I'm using `adapter.onGet(...).timeout()` and I see:

![image](https://user-images.githubusercontent.com/988270/39197863-4b5bccf8-47ee-11e8-8e3e-d194702f5a00.png)

This leads to the flow going to `utils.settle` instead of `result.then`, the promise not getting handled and erroring, and the original error getting lost, which is bad.

Possibly related: #122 

I believe adding the `typeof` check would do the intended functionality correctly here?

**Comment by ctimmerm** [comment]
Do you think you could write a failing test case for it?

**Comment by metrip** [comment]
On further inspection, it is not a feature of Node, but somehow specific to the VM that Jest sets up - Promise objects look a little different there, but I can't really tell why. Could be occurring in VM's created by other test frameworks, but I haven't had a look at them.

Writing test cases seems difficult as I can't find a good way to simulate functions like this.

However, as the intent here seems to be "if result.then is callable, settle result like a Promise", so the solution should be simple somehow.
