### ISSUE TITLE
[Question] is there a way to forwarding the request in the reply callback?

### ISSUE THREAD

**Issue by dinfer** [ctimmerm/axios-mock-adapter#137]
When dispatch request based on a field of the request body, how can I pass the request to server if I don't want to mock it?

```
adaper.onPost().reply(config => {
    switch(config.data.action) {
        case 'check_user'':
            // return mock data
        default:
            // how to forward this request here ?, returning a `[]` does not works
})
```

**Comment by davidlewallen** [comment]
I do not believe there is currently an implementation for that

**Comment by dinfer** [comment]
@davidlewallen Thanks, I know how to resolve that problem, 👍

**Comment by Manish2612** [comment]
@dinfer I am facing same issue. how did you solve it?
