### ISSUE TITLE
依赖太重了

### ISSUE THREAD

**Issue by a272121742** [ctimmerm/axios-mock-adapter#143]
1. 只能拦截Axios发送的请求，对于其他库发送的请求都无法拦截，没办法做到像[Mockjs](https://github.com/nuysoft/Mock)一样可以拦截所有的请求，不管是谁发的。
2. 只能拦截一个Axios实例，无法拦截其他实例
```javascript
import axios from 'axios';
const a2 = axios.create({baseURL: ''});
const AdapterMock = new MockAdapter(axios);
// AdapterMock可以拦截axios，但无法拦截到a2
```
这个能改进一点吗，让他的易用性和通用性更高点

**Comment by ctimmerm** [comment]
If you create the axios instance after the mock is set up, it will work as you want.

```js
import axios from 'axios';
const AdapterMock = new MockAdapter(axios);
const a2 = axios.create({baseURL: ''});
```
