### ISSUE TITLE
Url or payload mismatch just returns a 404

### ISSUE THREAD

**Issue by JeremyBradshaw7** [ctimmerm/axios-mock-adapter#147]
Unless the url & payload exactly matches the mock, you just get a 404 in the test failure. Is there any way to get the failure to show a diff of the expected requests against the actual requests? Otherwise it's difficult to debug.

Jasmine has stuff like expectGET which allows you to specify the expected requests in a test and it shows you if anything's different, even if there are additional requests made which were not expected, which I don't think you can do with mock.onGet (unless I'm missing something).

**Comment by jd-carroll** [comment]
This appears to be a duplicate of #116 

Can you please verify and close this issue
