### ISSUE TITLE
reply with different value when first call and second call the same API

### ISSUE THREAD

**Issue by ZHChen8397** [ctimmerm/axios-mock-adapter#155]
Hi, I've got a problem that, when I am doing acceptance testing, is it possible that I can mock the same API and reply different return value when I call the API first time and second times?

I tried to use chain, but it seems not work

    mock.onGet(serverDomain + ':3000/getProgramByUser?userName=' + 
        user.getUserName()).reply(200, response)
            .onGet(serverDomain + ':3000/getProgramByUser?userName=' + 
        user.getUserName()).reply(200, response2)

when I code like this, it will only return response2

**Comment by ctimmerm** [comment]
You can use `replyOnce` to only use the given response once.

```js
mock.onGet(serverDomain + ':3000/getProgramByUser?userName=' + 
    user.getUserName()).replyOnce(200, response) // this response will be given only once
        .onGet(serverDomain + ':3000/getProgramByUser?userName=' + 
    user.getUserName()).reply(200, response2)
```
