### ISSUE TITLE
Mock only some requests

### ISSUE THREAD

**Issue by dima74** [ctimmerm/axios-mock-adapter#158]
Could you say, please, how can I mock only some requests?

For example, only `/foo` and `/bar`, but any other request, for example `/zoo` will be handled by axios unchanged

Now if mock something, that any other request will return 404 error...

Thank you

**Comment by ctimmerm** [comment]
Use `onAny` without arguments to match any request and use `passThrough` to pass the requests through to axios.

From the readme:

```js
// Mock specific requests, but let unmatched ones through
mock
  .onGet('/foo').reply(200)
  .onPut('/bar', { xyz: 'abc' }).reply(204)
  .onAny().passThrough(); // Anything that wasn't matched above will be passed through to axios
```

**Comment by ahmethudaiaydin** [comment]
Hi,
I think this is very useful information and it does not exist on documentation. I tried to implement this for ongoing project and it gives 404. When I try to create issue, I saw that question. I think this should be in documentation part.

**Comment by kytosai** [comment]
I use another way is setting default ` onNoMatch: 'passthrough',`

```js
const mock = new MockAdapter(instAxios, {
  onNoMatch: 'passthrough', // ! set default to passthrough
});
```
