### ISSUE TITLE
How to assert data passed

### ISSUE THREAD

**Issue by createthis** [ctimmerm/axios-mock-adapter#172]
I have some code that mocks a POST request:

```js
mock.onPost(
   'example.com/foo',
   'id=123&keyword=somekey'
).reply(200, data);
```

This works. However, I'd really like to `assert` that `id` and `keyword` are being passed with the correct values.

Currently, if `id` or `keyword` change, the test fails, but it fails in a very obtuse way. It's difficult to figure out why the test fails.

Ideally, I would mock my POST without the data:

```js
mock.onPost(
   'example.com/foo',
).reply(200, data);
```

Then I would simply make an assertion verifying the data was passed as expected. Since I use `should.js`, this might look something like:

```js
mock.should.be.calledWithData('id=123&keyword=somekey');
```

The advantage here is that `should.js` would give me a nice string comparison of what was expected and what was actually sent, making debugging and updating much easier.

Is something like that possible with `axios-mock-adapter` currently? I didn't see it in the docs. Sorry if I missed it.

**Comment by ctimmerm** [comment]
You could make this work by replying with a callback:

```js
mock.onPost('example.com/foo').reply(function(config) {
  // assert here that config.url is correct
});
```

**Comment by jfo84** [comment]
@ctimmerm How can I keep it from throwing an unhandled promise rejection after asserting? Stuff like `return 201, config;` doesn't work

**Comment by jfo84** [comment]
This works:

```js
return Promise.resolve([201, result]);
```
