### ISSUE TITLE
How to match against get params?

### ISSUE THREAD

**Issue by chipit24** [ctimmerm/axios-mock-adapter#18]
I'm making the following request:

```
axios.get('/api', { params: { name: 'Bob' }})
...
```

And I'm trying to mock it like so:

```
mock.onGet('/api', { params: { name: 'Bob' } }).reply(200, 'Hello')
```

But it keeps returning a 404. I also tried the following to no avail:

```
mock.onGet('/api', { name: 'Bob' }).reply(200, 'Hello')
mock.onGet('/api?name=Bob').reply(200, 'Hello')
```

The only thing that matches it is:

```
mock.onGet('/api').reply(200, 'Hello')
```

How can I match against and mock `get` requests with specific query params?

**Comment by ctimmerm** [comment]
There's currently no shorthand for it, but you can achieve that by passing a callback function to `reply` and checking the params there:

```js
mock.onGet('/api').reply(function(config) {
  if (config.params.name === 'Bob') { // or check for deep equality with config.params
    return [200, 'Hello'];
  } else {
    return [400];
  }
});
```

I do plan to add support for giving the params to match to `onGet` though, as soon as I have some extra time (so that the first example you gave would work).

**Comment by CodinCat** [comment]
I think matching `mock.onGet('/api?name=Bob')` would make more sense since the test doesn't need to know how the request is being sent, `axios.get('/api', { params: { name: 'Bob' }})` or `axios.get('/api?name=Bob')`, it doesn't matter.

btw this is a really great library, thanks for your working.

**Comment by jayudhandha** [comment]
Hi Everyone,

I am doing similar stuff using for mocking my delete api.
Below is my Actual API call and mock function.

**API:**
```
axios.delete('/admin?user='+<DYNAMIC VALUE>).then(function(response) {
    console.log('Fail )
}).catch(function (error) {
    console.log('Fail )
});
```

**Mock:**
```
mock.onDelete('/admin?').reply(200,{ params: { foo: 'test'} });
```

I don't know how we can make this mock dynamic. For any value of user query param, i want to send this dummy output.

Any help?

Thanks,
Jayesh

**Comment by NearHuscarl** [comment]
@jayudhandha you can solve this by using regex to match url with dynamic query string. See my answer [here](https://stackoverflow.com/a/63672162/9449426) for more detail (live demo included)
