### ISSUE TITLE
subsequent on(...) after onAny are handled by onAny

### ISSUE THREAD

**Issue by escofield** [ctimmerm/axios-mock-adapter#197]
At the root ./api onAny mock to do nothing more than provide the console log with detailed information of the missing mock will be triggered if subsequent mock handlers are added. 

The example of such is:  
Mock loads, provided handlers for all known resources. 
example:
  ./api/users/id123
  ./api/users/id234

mock onAny  reply( config => console.log('config.url'); return [404] )

User then adds a new user (id777) causing the below code:
mock onGet('./api/users/id777').reply(...)

calls to fetch user id777 is then caught by onAny.

Due to onAny in my case only being informational for debugging purposes to identify what routes I have failed to mock, i can easily remove and all works.

However, it seems to me that either, better logging would be nice or a way to insert your handler in before the fall-through onAny..  I think the later is my recommendation as I am sure there are great uses of onAny more than just to add a console log.

I suppose this is a nice to have,  perhaps my mock is above and  beyond normal usage.

I suspect I could hack the private handler list and insert it myself..

**Comment by akatechis** [comment]
It sounds like what you want is to change the order of your handlers so that your GET/etc are matched first, then if nothing matches, the `onAny` handler will be called. From the README:

> Requests that do not map to a mock handler are rejected with a HTTP 404 response. Since handlers are matched in order, a final onAny() can be used to change the default behaviour
> ```
>  // Mock GET requests to /foo, reject all others with HTTP 500
> mock
>   .onGet('/foo').reply(200)
>   .onAny().reply(500);
> ```

In your case, you would change `reply(500)` to `reply(function () { ... })`

**Comment by ctimmerm** [comment]
This is working as intended.
