### ISSUE TITLE
Allow handler to return a promise

### ISSUE THREAD

**Issue by ericeslinger** [ctimmerm/axios-mock-adapter#20]
It would be raaaad if I could do something like this:

    mock.onPost(`/tests`).reply((data) => {
      return doSomething(data.data)
      .then((intermediate) => doSomethingElse(intermediate))
      .then((final) => final ? [200, final] : [404, {}])
      .catch((err) => [500, err]);
    });

instead, it looks like the .reply handler expects an immediate reply, instead of a deferred.

**Comment by ctimmerm** [comment]
Implemented in #21
