### ISSUE TITLE
Error 404 when RegExp

### ISSUE THREAD

**Issue by krystian50** [ctimmerm/axios-mock-adapter#209]
The request fails with `Request failed with status code 404` when the axios-mock-adapter is declared with:
` const articleUri = '/api/articles';
  const url = new RegExp(`${articleUri}/*`);
  mock.onGet(url).reply(function(config) {
...`

it works fine when declared with:
  `mock.onGet('/api/articles/1').reply(function(config) {
...`

So only for article with id `1`

The first example is taken from docs so I don't really know what is wrong here.

**Comment by gburning** [comment]
I'm also having trouble with using regex to match urls. As far as I can tell the regex is correct.

I'm using the other approach however:
```
mock.onGet(/\/api\/lorem\/ipsum\/\d+/).reply(200, data)
```
I've also tested a more forgiving expression:
```
mock.onGet(/\/api\/lorem\/ipsum\/.+/).reply(200, data)
```

Neither of them work. Am I missing something? Or is something broken?

**Comment by gburning** [comment]
My problem ended up not being regex-related. Seems to have been a problem with the context I was creating the `MockAdapter` instance in. I'm using Storybook (Vue) and was creating it outside the story scope but running the `onGet` method in the `created` lifecycle hook of the story component. Fixed it by creating the instance together with the method call.

So yeah, unrelated. But I'm leaving this here for posterity.

**Comment by andrewlaskey** [comment]
@gburning thanks! This was my exact issue. Moving things into `created` fixed my 404s.
