### ISSUE TITLE
Body defined as a string gets auto-converted to json

### ISSUE THREAD

**Issue by jay-jlm** [ctimmerm/axios-mock-adapter#215]
```
axiosInstanceMock.onPost(/\.*/).reply(201, '{ "path": "upload_path" }');
```

`result.data` for the request above is of type `object`, however when using axios on the website I receive this data as a string from the server.

**Comment by ctimmerm** [comment]
This conversion is done by a default response transformer in axios itself: https://github.com/axios/axios/blob/master/lib/defaults.js#L57-L65.
