### ISSUE TITLE
It is possible to use a wildcard for the URL?

### ISSUE THREAD

**Issue by javierguzman** [ctimmerm/axios-mock-adapter#218]
Hello everybody!

I would like to know if it is possible to mock certain urls using wildcards, kind of all urls that start by \auth ; Can I do something like \auth\*?

Thank you in advance and regards.

**Comment by gburning** [comment]
You can use regex. Something like:
```mock.onGet(/\/^.+\/auth\/.+$/).reply(204, [])```

My knowledge of regex isn't great. You might want to be more specific in what you allow before and after `/auth/` but that's a start.

**Comment by javierguzman** [comment]
Thank you!  At the end I have used as URL new RegExp(`url/*``);

I close this.
