### ISSUE TITLE
Passing a function to reply returns function instead of Object

### ISSUE THREAD

**Issue by developeruz** [ctimmerm/axios-mock-adapter#231]
The code I am trying to test:
```
my_action: async (params) => {
    return axios.post('my/action', params).then((response) => {
      ... do something with response
    })
  },
```
This one works fine:
```
mock.onPost('my/action').reply(200, { data: 'test' });
```
But this one dosen't:
```
mock.onPost('my/action').reply(200, function (config) {
    return [200, { data: 'test' }]
})
```
The error I am getting is `Cannot read property ... of undefined` because in the second case `then((response)` recives `response` as `undefined`. What am I doing wrong? How to return resolved promise when replay passed as a function?

**Comment by developeruz** [comment]
If I pass function it returns function, not the result of it
```
axios.interceptors.response.use((res) => {
  if(typeof res.data === "function") {
     console.log(res.data())
     return res.data()
  }
  console.log(res.data)
  return res.data
}, (error) => {
})
```
Seems to be a bug

**Comment by ctimmerm** [comment]
> ```js
> mock.onPost('my/action').reply(200, function (config) {
>     return [200, { data: 'test' }]
> })
>```

If you pass a function to reply, it's the first and only argument that reply accepts.
