### ISSUE TITLE
How can I isolate tests while using a default axios instance?

### ISSUE THREAD

**Issue by berrybell** [ctimmerm/axios-mock-adapter#233]
I am using `jest` to run my tests. My components use `axios` to make fetch requests. I have a default instance set up like this:

```javascript
const instance: AxiosInstance = axios.create({
  baseURL: URL
});
```

Inside my tests, I am mocking it with `axios-mock-adapter` like this:

```javascript
it('should render correctly', () => {
  const mock = new MockAdapter(instance);
  mock.onGet('/some-api-endpoint').reply(200, fixtureData);
  expect(render(smth)).toMatchSnapshot();
});
```

However, I am getting weird side effects such as tests passing/failing even when I disable some parts of the code which indicates to me that mocks interfere with each other. Is there anything I should do about it?

**Comment by ctimmerm** [comment]
Since adding a mock adapter to an instance is a global change, each test needs to clean up after itself so that the mock doesn't carry over to other tests.

The easiest way to do this is to use `beforeEach` and `afterEach`:

```js
let mock;

beforeEach(() => {
  mock = new MockAdapter(instance);
});

afterEach(() => {
  // This restores the original adapter that was there before installing the mock adapter and thus removes the mocking behavior
  mock.restore();
});

it('should render correctly', () => {
  mock.onGet('/some-api-endpoint').reply(200, fixtureData);
  expect(render(smth)).toMatchSnapshot();
});
```
