### ISSUE TITLE
Chaining on timeouts doesn't work as it returns void.

### ISSUE THREAD

**Issue by RichardWright** [ctimmerm/axios-mock-adapter#236]
Hi!

How can timeouts be chained? Eg to simulate a timeout which then responds after more than one timeout? 

Code below to show an example:

`
//always returns timeout, never returns the get
mock.onGet('/test-url').timeout()
mock.onGet('/test-url').replyOnce(200, { test: 'test!' }

//returns timeout once, goes to reply once.
mock.onGet('/test-url').timeoutOnce()
mock.onGet('/test-url').replyOnce(200, { test: 'test!' }
`

**Comment by ctimmerm** [comment]
This has been fixed in 8215717b52565d2a1995dc23de01492d9dbaaf9c
