### ISSUE TITLE
How to mock options call

### ISSUE THREAD

**Issue by GabLeRoux** [ctimmerm/axios-mock-adapter#239]
Hello there, I was mocking a few api calls, and I'm using an `options` call somewhere precisely. Is there a way to mock `options` other than using `onAny`?

https://github.com/ctimmerm/axios-mock-adapter/blob/71cd221af612eac73178611317d466d66aba06f5/types/index.d.ts#L44-L63

I would have expected something like `onOption: RequestMatcherFunc` or something like that.

**Comment by ctimmerm** [comment]
Fixed in #240
