### ISSUE TITLE
URL didnt matching in Get request

### ISSUE THREAD

**Issue by SubhuMS** [ctimmerm/axios-mock-adapter#24]
Hi Team,

I have a click function for fetching the records through API call, the function looks like below,

```
onClick(rollNo){
					axios({
						url: '/api/getStudentDetail/'+rollNo,
						method: 'get',
						headers: {                	
							'Content-type': 'text/csv'
						}	
					}).then(function (successData) {
		                                console.log(successData.data);
					}.bind(this)).catch(function (errorData) {         
                                                console.log(errorData.data);
					}.bind(this));
}
```

I am trying to mock this axios call using axios mock adapter as below,

	it('should test StudentContainer ', function (done) {
		const wrapper = shallow(<StudentContainer />);		
		const button= wrapper.find('button').at(0);
		var rollNo = 'A016SS1245';
		button.simulate('click', [rollNo]);	
		mock.reset();
		mock.onGet('/api/getStudentDetail/').reply(200, { 
		 			firstName: 'John',
                                        lastName: 'smith'
		});
		axios.get('/api/getStudentDetail/')
			.then(function(response) {
				console.log(response);
			});         
		done();					
	});		

While running this testcase, it every time execute the catch block, rather than then block. Can anyone help me on how to mock this axios call using axios mock adapter.

**Comment by ctimmerm** [comment]
I can spot two possible problems:

1. The URL you're mocking out is different from the one that is called in `onClick`.
The one in `onClick` is `'/api/getStudentDetail/' + rollNo` while you register a mock handler for just `/api/getStudentDetail/`, so a matching handler will not be found.

2. You simulate the click *before* you've registered a mock handler, so at the point the request is made, there will be no matching mock handler yet.

I'll close this one for now, please reopen it if you can't get it to work.

**Comment by SubhuMS** [comment]
@ctimmerm ,

Thanks for your reply,

I tried as you said, but still its not mocking the promise. i tried changing the url and mock before the click event simulate. So i will reopen this issue.
