### ISSUE TITLE
Passthrough everything not mocked

### ISSUE THREAD

**Issue by thany** [ctimmerm/axios-mock-adapter#243]
I'm trying to achieve passing through all requests that aren't mocked:
```javascript
mockAdapter.onAny().passThrough();
```

However, **I cannot do this at the end** because I've got several modules all installing their own mocks. I cannot know which is the last one without some really hairy code (*if* I can get that to work).

I would rather put this at the start as a suggestion to axios-mock-adapter to "let everything pass through that isn't being mocked". As a sort of catchall-handler. In general, catch-alls are traditionally specified at the end of something.

I've been looking through the code, and it seems like the first handler that matches a request, will be used. It feels like this is incorrect, because you might also want to do something like this:
```javascript
mockAdapter
  .onGet('/users').reply([ user1, user2, ... ]) 
  .onGet('/users', { id: 1 }).reply(user1);
```
It looks elegant, because you go more specific with every next mock. However, in the above sample the second mock will *never* be used. Now, it's easy to say "just reverse them", but what if two separate modules install mocks by themselves? Then, it'll depend on import order, which is an antipattern.

I would propose searching for handlers not by the logic "find the first that happens to match the request" but by logic "find the most specific one that matches the request". So achieve that, it's probably best to order the handlers by specificity and look for a suitable handler starting at the top. Ordering by specificity could be achieved in a CSS-kind-of way.

**Comment by ctimmerm** [comment]
Having the ability to pass through everything without a matching handler is being implemented  in https://github.com/ctimmerm/axios-mock-adapter/pull/237.

Matching handlers in the order they're specified in is I think the most intuitive thing to do, every request router that I know of also works that way. Next to not being intuitive, ordering by specificity is difficult to do once we have more advanced ways to do matching, e.g. if you match by regex or by a function that returns true or false.
