### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by ckknight** [ctimmerm/axios-mock-adapter#244]
It appears that there hasn't been a release for 7 months now and there is code within `master` (particularly regarding how errors are created) that would be wonderful to use.

**Comment by ctimmerm** [comment]
The UMD bundle is currently several times bigger than it was in the last release, I first want to fix that before doing a new release.

**Comment by benoitdion** [comment]
👍 would be great to get a release with `asymmetricMatch` support

**Comment by luceleaftea** [comment]
Not to just "+1", but a new release would be awesome as I would love to use the passthrough options.  Is there anything we can do to help with the UMD bundle in order to help prep for a release?

**Comment by ctimmerm** [comment]
https://github.com/ctimmerm/axios-mock-adapter/releases/tag/v1.18.0
