### ISSUE TITLE
URL didnt matching in Get request 

### ISSUE THREAD

**Issue by SubhuMS** [ctimmerm/axios-mock-adapter#25]
Hi Team,

I have a click function for fetching the records through API call, the function looks like below,

```
onClick(rollNo){
                    axios({
                        url: '/api/getStudentDetail/'+rollNo,
                        method: 'get',
                        headers: {                  
                            'Content-type': 'text/csv'
                        }   
                    }).then(function (successData) {
                                        console.log(successData.data);
                    }.bind(this)).catch(function (errorData) {         
                                                console.log(errorData.data);
                    }.bind(this));
}
```

I am trying to mock this axios call using axios mock adapter as below,

```
it('should test StudentContainer ', function (done) {
    const wrapper = shallow(<StudentContainer />);      
    const button= wrapper.find('button').at(0);
    var rollNo = 'A016SS1245';
    mock.reset();
    mock.onGet('/api/getStudentDetail/' + rollNo).reply(200, { 
                firstName: 'John',
                                    lastName: 'smith'
    });
            button.simulate('click', [rollNo]); 
    axios.get('/api/getStudentDetail/')
        .then(function(response) {
            console.log(response);
        });         
    done();                 
});     
```

While running this testcase, it every time execute the catch block, rather than then block. Can anyone help me on how to mock this axios call using axios mock adapter.

@ctimmerm, also i tried as you said in previous post its not working, and this is the respone i get when i run the test script,

```
Error: the object {
```

 "config": {
   "adapter": [Function]
   "data": [undefined]
   "headers": {
     "Accept": "application/json, text/plain, _/_"
   }
   "maxContentLength": -1
   "method": "get"
   "timeout": 0
   "transformRequest": {
     "0": [Function]
   }
   "transformResponse": {
     "0": [Function]
   }
   "url": '/api/getStudentDetail/'
   "validateStatus": [Function]
   "withCredentials": [undefined]
   "xsrfCookieName": "XSRF-TOKEN"
   "xsrfHeaderName": "X-XSRF-TOKEN"
 }
 "status": 404
 was thrown, throw an Error :)

Could you please help me in resolving this issue.

**Comment by alex-paterson** [comment]
Your `onClick` function is making a request to` '/api/getStudentDetail/'`, suggesting the `rollNo` argument is not defined.
