### ISSUE TITLE
.onAny() not working as expected

### ISSUE THREAD

**Issue by chipit24** [ctimmerm/axios-mock-adapter#26]
I have my mocks set up like to:

```js
mock
  .onGet('/foo').reply(200)
  .onAny().reply(500);
```

However, when I make a request to `/bar`, a `404` code is returned instead of my specified `500`. Changing this to `.onAny('/bar')` or `.onAny(/.*/)` works as expected.

I am using axios v0.14.0 and axios-mock-adapter v1.6.1.

**Comment by ctimmerm** [comment]
Calling `onAny` without arguments is only supported since 1.7.0.

**Comment by chipit24** [comment]
Ah, thanks! I looked through the release log but didn't see it referenced since v1.1.0!

**Comment by ctimmerm** [comment]
Yeah, the feature was included with some other, larger changes. I'll update the release notes to mention it.

**Comment by chipit24** [comment]
I updated, and now I'm seeing something strange. `onAny` now catches all requests, but if the request uses an absolute URL it truncates/modifies the url property of the config that's passed into the function.

Following the example above, if I change my `onAny` call to...
```js
.onAny().reply((config) => {
  console.log(config.url);
  return [500];
});
```

... and make a request to `http://example.com/bar`, an empty string is printed to the console. `http://example.com/foobar` prints `r`.

**Comment by ctimmerm** [comment]
If I add the following example to `basics.spec.js`, it works as expected:

```js
  it('works with absolute URLs', function() {
    mock.onAny().reply(function(config) {
      console.log(config.url); // logs "http://www.example.org/bar"
      return [200];
    });

    return instance.get('http://www.example.org/bar')
      .then(function(response) {
        expect(response.status).to.equal(200);
      });
  });
```

I'm not really sure what's different in the code you've pasted. Could you maybe start from the above test and change it to resemble the code that's failing for you?

**Comment by chipit24** [comment]
@ctimmerm In the example spec you gave, add `instance.defaults.baseURL = 'http://www.foobar.com';` to the beginning and you'll see that what gets logged is `g/bar`, instead of the expected `http://www.example.org/bar`.

**Comment by ctimmerm** [comment]
OK, thanks for the explanation, now I get it. I'll fix it

**Comment by ctimmerm** [comment]
I just pushed a new release, can you check if we're all good now?
