### ISSUE TITLE
auto-import in vscode wants import MockAdapter from 'axios-mock-adapter/types';

### ISSUE THREAD

**Issue by xenoterracide** [ctimmerm/axios-mock-adapter#270]
auto-import in vscode wants `import MockAdapter from 'axios-mock-adapter/types';`

this is not correct/doesn't work instead it needs to be `'axios-mock-adapter';`

obviously I'm hand correcting it, but I suspect this is a layout problem of the published artifact or a naming issue of the .d.ts file. It doesn't affect compiletime, only runtime. So it's a bit weird imho, and the only library I've seen this with.

**Comment by oless** [comment]
@xenoterracide Could you please elaborate how did you hand correct this?

**Comment by marcbachmann** [comment]
The type setup in this module changed a bit by now. I'll close this for now
