### ISSUE TITLE
Question: Handle response type blob

### ISSUE THREAD

**Issue by qapla47** [ctimmerm/axios-mock-adapter#275]
I have a get request that downloads a file. It has a configuration of 
```javascript
const downloadFile = fileId => (dispatch, getState) => {
  const token = getState().auth.token
  let config = {
    responseType: 'blob',
    headers: { 'Content-Type': 'application/zip' }
  }
  return axios
    .get('download/endpoint`, config)
    .then(res =>
      let url = window.URL.createObjectURL(res.data)
      ... other stuff related to downloading files ...
    })
    .catch(err => { error block })
```
I mock my instance, and create a fake blob
```javascript
let blob = new Blob([], {type: 'application/zip' })
let fakeFile = blob
```
and then create my request
```javascript
mock
  .onGet('download/endpoint')
  .reply(config => {
    return [
      200,
      fakeFile,
      { Header Configuration }
    ]
  })
```
However, when my response is received, my data no longer contains a Blob. 
```javascript
res.data instanceof Blob
```
Checking the instance of returns false, while in my actual implementation, it returns true
This prevents the 
```javascript
window.URL.createObjectURL(res.data)
```
from functioning as it is expecting a Blob, not an object. 

How can I get this test to pass?

**Comment by erykpiast** [comment]
I have a similar issue. I think that's all because [the case of `Blob` isn't correctly handled here](https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/handle_request.js#L6-L10). If we add a simple check like `utils.isBlob(data)` and pass it raw (instead of making a deep copy), everything should work as expected.

**Comment by thefat32** [comment]
> I have a similar issue. I think that's all because [the case of `Blob` isn't correctly handled here](https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/handle_request.js#L6-L10). If we add a simple check like `utils.isBlob(data)` and pass it raw (instead of making a deep copy), everything should work as expected.

Please merge this fix!
