### ISSUE TITLE
responseUrl should be responseURL

### ISSUE THREAD

**Issue by createthis** [ctimmerm/axios-mock-adapter#278]
I'm seeing a difference between `axios-mock-adapter` and using `axios` on Chrome using the following pseudocode:
```js
try {
  const response = await axios.put(some_url);
} catch (e) {
```

Using `axios_mock_adapter` the path is:
```js
e.response.request.responseUrl
```

However on Chrome it is:
```js
e.response.request.responseURL
```

This is pretty annoying because I have to test both on the client when simulating 302 redirects.

**Comment by ctimmerm** [comment]
Will be fixed by #287
