### ISSUE TITLE
Would love a release of the latest commits!

### ISSUE THREAD

**Issue by tjefferson08** [ctimmerm/axios-mock-adapter#280]
Hey! I see there are a few commits on master since the last release (1.18.2)

Here's the diff: https://github.com/ctimmerm/axios-mock-adapter/compare/v1.18.2...master

I'd really appreciate a new npm release (1.18.3?); I'm especially excited to get [`onNoMatch: 'throwException'`](https://github.com/ctimmerm/axios-mock-adapter/commit/a52b450d95479a104d46294f46271c105af31647)

For anyone else wanting the latest, it seems that you can install this package straight from the github master branch and it all works nicely (I guess because there's no bundling/minification, etc)

```sh
npm install ctimmerm/axios-mock-adapter#master
```

**Comment by ctimmerm** [comment]
https://github.com/ctimmerm/axios-mock-adapter/releases/tag/v1.19.0 released.

**Comment by tjefferson08** [comment]
@ctimmerm thank you! 🙏
