### ISSUE TITLE
Mocking axios.all()

### ISSUE THREAD

**Issue by untemps** [ctimmerm/axios-mock-adapter#31]
Hi.
Is there a way to mock multiple get requests originally managed by the all() method?
I saw the last section of the doc ("Composing from multiple sources with Promises:") but I'm not sure this is what I need and if so how to deal with it.
Any suggestions?
Thanks.

**Comment by ctimmerm** [comment]
`axios.all` is just an alias for `Promise.all`.
Could you give an example so that I can get a better idea of what you're trying to do?

**Comment by untemps** [comment]
Sure.
Here is my action creator :

```javascript
export const fetchData = () => {
    return (dispatch) => {
        return axios.all([
            axios.get(`../file1.json`),
            axios.get(`../file2.json`),
            axios.get(`../file3.json`)
        ]).then(
            axios.spread(
                ({data: file1}, {data: file2}, {data: file3}) => {
                    dispatch({
                        type: FETCH_DATA_SUCCESS,
                        file1, file2, file3
                    });
                }
            ),
            error => {
                dispatch({
                    type: FETCH_DATA_ERROR,
                    error: error.message
                });
            }
        );
    };
};
```

**Comment by ctimmerm** [comment]
Since they are get requests like any other, they can be mocked with `mock.onGet`:
```js
mock
  .onGet('../file1.json').reply(200, { data: file1 })
  .onGet('../file2.json').reply(200, { data: file2 })
  .onGet('../file3.json').reply(200, { data: file3 });
```

**Comment by untemps** [comment]
Thanks. That helps.
I don't know how to access my local files while testing but it's another story.
