### ISSUE TITLE
Unable to import axios-mock-adapter

### ISSUE THREAD

**Issue by karavadip** [ctimmerm/axios-mock-adapter#319]
unable to import axios-mock-adapter tried the 3 different ways of importing
![image](https://user-images.githubusercontent.com/6555536/139505122-a197e1b5-e62c-4a3b-a8eb-b69b12688f55.png)
![image](https://user-images.githubusercontent.com/6555536/139505136-d5a84ee7-1777-474a-b9d1-e12485c9c7bb.png)
![image](https://user-images.githubusercontent.com/6555536/139505155-4abdf435-a839-4f19-8ad2-565c55258f52.png)

Please fix the issue and help us. I see some other people also reporting this issue, on a different thread which is closed (https://github.com/ctimmerm/axios-mock-adapter/issues/289) down. Hence opening a new case. Thanks for your attention.

**Comment by ctimmerm** [comment]
This is likely an error in your setup. axios-mock-adapter lists axios as a peer dependency and the error you're seeing indicates that axios-mock-adapter is not able to import axios correctly.
