### ISSUE TITLE
on 1.20.0 IE11 breaks

### ISSUE THREAD

**Issue by SylRob** [ctimmerm/axios-mock-adapter#324]
(for my work I still have to support IE11)

the culprit is [is-blob](https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/utils.js#L6)

the imported script is not es5 compiled (just because it use an arrow function...)
```js
module.exports = value => {
	if (typeof Blob === 'undefined') {
		return false;
	}

	return value instanceof Blob || Object.prototype.toString.call(value) === '[object Blob]';
};
```
a really simple fix would be to just create a `isBlob` function in the utils file

there is an other fix, add `is-blob` into the exclude setting of babel-loader 
something like that : 
```js
{
    test: /\.js$/,
    exclude: [/node_modules\/(?!(is-blob)\/).*/],
    loader: 'babel-loader',
  },
```
(this seem to work for me so far)
(I use webpack with babel)

I don't know if you care about IE11 support but this is just to let you guys know.
if you don't want to support IE11 a nice compromise would be to put something in the Readme ?

**Comment by marcbachmann** [comment]
sorry, just use a correct babel setup. This module only supports newer runtimes.
