### ISSUE TITLE
Inspecting request body?

### ISSUE THREAD

**Issue by claytonrcarter** [ctimmerm/axios-mock-adapter#33]
I am looking for a way to verify that the JSON in my request is structured properly for the API on the server.  (I don't want to match routes or methods against certain request parameters.)  Is the only way to inspect the request data via the `config.data` property in the `.reply()` method?  

For example, I'm doing something like this now:
```
mock.onPost().reply( ({data}) => { 
    expect(data.items.length).not.toBe(0);
    expect(data.title).toBe("my test title");
    // etc...
    done();
});
```

but using `.reply()` for this seems somewhat counterintuitive and I'm wondering if I'm missing something.

**Comment by iamkirkbater** [comment]
I'm also looking for the exact same thing.  I'd be happy to look into adding a way to do this if it's not already built in and I'm just missing it.

**Comment by ctimmerm** [comment]
There's no dedicated method for this, did you have something in mind as a proposal?
I was thinking it could be like this:

```js
mock.onPost()
  .do(config => {
    // do you expectations or other side effects here
  })
  // We can't just leave the request hanging and need to reply something
  .reply(200);
```

**Comment by tb** [comment]
@claytonrcarter Idea with 'do' looks interesting. ATM I tried to write test that checks params like this (I am using jest):

```
test('fetch data success', () => {
  axiosMock.onGet(/api\/endpoint/)
    .reply(({ params }) => {
      expect(true).toEqual(false);
      return [200, data];
    });

  const actions$ = ActionsObservable.of(actionCreators.fetchData(id));

  return fetchDataEpic(actions$, store)
    .bufferTime(100)
    .toPromise()
    .then((res) => {
      expect(res).toEqual([
        actionCreators.fetchDataStarted(null, { id }),
        actionCreators.fetchDataSuccess(data, { id }),
      ]);
    });
});
```

The problem is that the expect inside reply callback is raising http exception that looks like http error... so I never sue the `expect(true).toEqual(false);` error message - which should fail the test instantly. Do you think the `do` could fix this use case?

**Comment by claytonrcarter** [comment]
@ctimmerm If the idea of a `do()` is to make test/assertion code more concise, could it imply how to reply based on the return of `do()`? If `do` doesn't return anything, reply with a default of `200`, otherwise use whatever is returned from `do` to create the reply?
For example, based on @tb example:
```js
axiosMock.onGet(/api\/endpoint/)
    .do(() => {
      expect(true).toEqual(false);
    });
```
would automatically reply with a `200`. Whereas:
```js
axiosMock.onGet(/api\/endpoint/)
    .do(() => {
      expect(true).toEqual(false);
      return [404, data];
    });
```
would reply with a `404`, etc.
Just some ideas.

**Comment by tb** [comment]
ATM I will test params using this:

    test('fetch data success', () => {
      const requests = [];
      axiosMock.onGet(/api\/endpoint/)
        .reply(({ url, params }) => {
          requests.push({ url, params });
          return [200, data];
        });

      const actions$ = ActionsObservable.of(actionCreators.fetchData(id));

      return fetchDataEpic(actions$, store)
        .bufferTime(100)
        .toPromise()
        .then((res) => {
          expect(requests).toMatchSnapshot();
          expect(res).toEqual([
            actionCreators.fetchDataStarted(null, { id }),
            actionCreators.fetchDataSuccess(data, { id }),
          ]);
        });
    });

It would be nice to have `do` to to put there `requests.push({ url, params });`.. or even nicer to be able to skip it and use just `expect(axiosMock.requests).toMatchSnapshot();`

**Comment by MisRob** [comment]
+1

**Comment by iamkirkbater** [comment]
I've started using Proxyquire, and with that I've just been feeding my own fakes, mocks and stubs to the axios object, rather than use an outside mock anymore.  For just requesting the passed parameters, this has proven quite useful.

**Comment by thylux** [comment]
I would like to use .do() to handle data for a fake API database.

It seems it could have many use cases.

**Comment by antony** [comment]
I'm of the opinion that allowing a function as the 'body' parameter gives the greatest flexibility. If you returned true from that function it would be a match, and if not, you could throw an error with a message, i.e:

```
context('valid parameters', () => {
    beforeEach(() => {
      mock = new MockAdapter(axios)
    })

    it('test something', async () => {
      mock
        .onPost(`/mail/send`, request => {
          return request.name === 'Antony Jones'
        })
        .reply(202)

      response = await service.send({
        name: 'Antony Jones',
        email: 'antony@example.com'
      })
    })

    afterEach(() => {
      mock.restore()
    })
  })
```

**Comment by ctimmerm** [comment]
To verify if the request body is correct, [history](https://github.com/ctimmerm/axios-mock-adapter#history) can be used.
