### ISSUE TITLE
axios instance is not mocked

### ISSUE THREAD

**Issue by syffs** [ctimmerm/axios-mock-adapter#335]
**Versions:**
- NodeJS: 16.13.0
- axios: 0.26.1
- axios-mock-adapter: 1.20.0
- Typescript: 4.6.3
- system: WSL Ubuntu 18.04
-------------
As in title, here is a [repro](https://github.com/syffs/jest-mongodb-demo) with [axios test](https://github.com/syffs/jest-mongodb-demo/blob/3ecd2f484f4e54ce18650a481429593e2fc632b3/tests/api/sample-api.test.ts#L38). Just clone, then `yarn install && yarn build && yarn test`.
Using `onNoMatch: "throwException"` has no effect.

is there a way to somehow mock axios globally (for every instance) ?

**Comment by marcbachmann** [comment]
There's currently no way to mock all axios instances as it doesn't inherit the interceptors.
You'd need to track the instances yourself and call the mock on all of them 🤔 
There are no plans to add such support.
