### ISSUE TITLE
Error in new version v1.21.1 -> new MockAdapter(axios)

### ISSUE THREAD

**Issue by henriqueholtz** [ctimmerm/axios-mock-adapter#339]
Error at new version: [v1.21.1](https://github.com/ctimmerm/axios-mock-adapter/releases/tag/v1.21.1)

Code: 

```
import axios from 'axios';
import MockAdapter from 'axios-mock-adapter';

var mock = new MockAdapter(axios);
```

My package.json:

```
[...]
"axios": "^0.27.2",
"axios-mock-adapter": "^1.21.1",
[...]
```

My project: https://github.com/SharebookBR/sharebook-frontend-next

![image](https://user-images.githubusercontent.com/51380783/172779311-a73bcd44-97be-4634-8efa-b09d3f49af29.png)

**Comment by ctimmerm** [comment]
Can you confirm that it does work on v1.20?

The place where the error occurs hasn't changed recently and would indicate there's something wrong with your axios setup (`axios.defaults` being undefined).

**Comment by henriqueholtz** [comment]
@ctimmerm 

With the version `1.20.0` I receive this error:

_(axios version: 0.27.2)_

![image](https://user-images.githubusercontent.com/51380783/172798737-ffbdb830-9074-464b-9946-76c9ecbcb2e2.png)

**Comment by ctimmerm** [comment]
I'm pretty sure this is an error with your TypeScript setup and not with this library, so I'll close the issue for now. Please reopen it if you're able to reproduce it in a test.

**Comment by mustafahlvc** [comment]
Hi @henriqueholtz did you findout a solution?
