### ISSUE TITLE
Correct way to cleanup mock

### ISSUE THREAD

**Issue by npoirey** [ctimmerm/axios-mock-adapter#34]
I had side effects between tests because of the mocks. I had 2 files on the following model:

```
import axios from 'axios'
import MockAdapter from 'axios-mock-adapter'

const mock = new MockAdapter(axios)

describe('eventsActions', () => {

  afterEach(() => {
    mock.reset()
  })

  describe('changePreferences', () => {
    it('should call /api/users/preferences and dispatch events', (done) => {
      mock.onPost('/api/users/preferences')
        .reply(200)
...
```

When run alone, each file end with success but when run together, the calls to one url are 404.
I suspected a side effect due to poor cleaning and I looked at the tests on this repo. My tests now works by removing the afterEach and adding
```
beforeEach(() => {
    mock = new MockAdapter(axios)
  })
```

So, problem solved, but I am curious. Is this the intended use ? When am I supposed to use reset() and restore() ?

Thank you

**Comment by i-aakopian** [comment]
Also having this issue as well.

**Comment by colbycheeze** [comment]
I came  here to ask about this...guess it's not just me. Seems like the `reset()` isn't actually working?

**Comment by ctimmerm** [comment]
`reset` and `restore` do two different things.

From the readme:
> `reset` is different from `restore` in that restore removes the mocking from the axios instance completely, whereas reset only removes all mock handlers that were added with onGet, onPost, etc. but leaves the mocking in place.

So:
* `reset` removes all registered mock handlers. It leaves you with an empty mock, i.e. any request made will result in a 404.

* `restore` restores the axios instance as it was before and removes the mocking behavior altogether. If you're using a global axios instance you want to use this in `afterEach` to remove the mocking behavior before other tests are run.

Let me know if this is not clear or if you think either of the two isn't working correctly.

**Comment by colbycheeze** [comment]
I've tried using both in `beforeEach` and `afterEach`, and neither seem to work. Reset leaves all previous mocks in place instead of resetting them, and restore causes all future mocks to be disabled.

**Comment by colbycheeze** [comment]
I set up a little test:
```
describe('Axios Mock Adapter', () => {
  const mock = new MockAdapter(axios)
  
  it('successfully mocks an actual network request from happening', async () => {
    // const mock = new MockAdapter(axios)

    mock.onGet('/users').reply(200, {
      users: [
        { id: 1, name: 'Samuel Muthafuckin Jackson' },
      ],
    })

    const users = await getUsers()
    expect(users).toMatchObject({ users: [{ id: 1, name: 'Samuel Muthafuckin Jackson' }] })
  })

  it('mocks another request', async () => {
    mock.reset()

    mock.onGet('/users').reply(404, {
      errors: [
        { message: 'user not found' },
      ],
    })

    const users = await getUsers()
    expect(users).toMatchObject({ errors: [{ message: 'user not found' }] })
  })
})
```

This fails with:
![screen shot 2017-02-16 at 11 45 23 am](https://cloud.githubusercontent.com/assets/8884298/23033376/6e8cdb96-f43d-11e6-8818-f77bb464e045.png)

**Comment by ctimmerm** [comment]
I can't really tell from your example if it's working correctly or not. In the first screenshot the request failed with status 404 and it seems like it's supposed to do so. In the second screenshot there's a syntax error, which is probably an error in your test code?

**Comment by colbycheeze** [comment]
Okay my mistake, I realized that I need to use try/catch for anything other than 200. Didn't realize an actual error was thrown otherwise.

```js
  it('mocks another request', async () => {
    mock.reset()

    mock.onGet('/users').reply(666, {
      errors: [
        { message: 'demons are invading' },
      ],
    })

    try {
      await getUsers()
    } catch (error) {
       expect(error.response.data).toMatchObject({ errors: [{ message: 'demons are invading' }] })
    }
  })
```

**Comment by npoirey** [comment]
Thank you for your response.
If I understand correctly, I should be able to use reset() in afterEach() so that I'm sure that every test in the file has only its stubs set up, leaving the mock in place but removing handlers, and restore() in after() so that I don't pollute other tests having axios mocked when I don't expect it to be ?

if so, there is definitly something unexpected going on. I Have 2 tests files, identical except for the describe text:

```javascript
import axios from 'axios'
import MockAdapter from 'axios-mock-adapter'
import chai from 'chai'

const expect = chai.expect

describe('test file 1', () => {
  let mock = new MockAdapter(axios)

  afterEach(() => {
    mock.reset()
  })

  after(() => {
    mock.restore()
  })

  it('test case 1', (done) => {
    mock.onGet('/api/events').reply(200, [{ id: 1 }])
    axios.get('/api/events')
      .then((response) => {
        expect(response.data).to.eql([{ id: 1 }])
        done()
      })
      .catch((err) => {
        done(err)
      })
  })

  it('test case 2', (done) => {
    mock.onGet('/api/events').reply(200, [{ id: 2 }])
    axios.get('/api/events')
      .then((response) => {
        expect(response.data).to.eql([{ id: 2 }])
        done()
      })
      .catch((err) => {
        done(err)
      })
  })
})
```

here are the results in isolation:
![image](https://cloud.githubusercontent.com/assets/6019178/23039161/fa576516-f48c-11e6-89ee-0054ac655499.png)
![image](https://cloud.githubusercontent.com/assets/6019178/23039183/08823ba2-f48d-11e6-869c-2247f58b85d5.png)

and here are the results when run together:
![image](https://cloud.githubusercontent.com/assets/6019178/23039388/a0538a80-f48d-11e6-80be-2db31de6652a.png)



if I remove the call to restore in the 2 files, ie:
```javascript
  afterEach(() => {
    mock.reset()
  })

  after(() => {
    //mock.restore()
  })
```

I get the following:
![image](https://cloud.githubusercontent.com/assets/6019178/23039399/aa2c2cf6-f48d-11e6-8162-4dfde2e63cc2.png)

**Comment by ctimmerm** [comment]
You're creating the mock in the describe function, which is executed before any of the tests are run.
You need to create it in `before` instead.

```js
import axios from 'axios'
import MockAdapter from 'axios-mock-adapter'
import chai from 'chai'

const expect = chai.expect

describe('test file 1', () => {
  let mock

  before(() => {
    mock = new MockAdapter(axios)
  })

  afterEach(() => {
    mock.reset()
  })

  after(() => {
    mock.restore()
  })

  it('test case 1', (done) => {
    mock.onGet('/api/events').reply(200, [{ id: 1 }])
    axios.get('/api/events')
      .then((response) => {
        expect(response.data).to.eql([{ id: 1 }])
        done()
      })
      .catch((err) => {
        done(err)
      })
  })

  it('test case 2', (done) => {
    mock.onGet('/api/events').reply(200, [{ id: 2 }])
    axios.get('/api/events')
      .then((response) => {
        expect(response.data).to.eql([{ id: 2 }])
        done()
      })
      .catch((err) => {
        done(err)
      })
  })
})
```

**Comment by npoirey** [comment]
I see, I'm probably missing a few point on how tests are run.
It works fine this way and make more sense now, thank you for your help.

**Comment by michael-customlbs** [comment]
Does anyone have a neat helper function that I can call in describe to register all the callbacks to do the resetting?
Something like:
```
describe('Test', () => {
  let mock = initMock(axios)
  ...
}
```

**Comment by kevinch** [comment]
FYI, with Jest i had it working like this:
```
let mock
let store

beforeEach(() => {
  mock = new MockAdapter(axios)
  store = mockStore({})
})

afterEach(() => {
  mock.reset()
})
```

**Comment by berkslv** [comment]
> FYI, with Jest i had it working like this:
> 
> ```
> let mock
> let store
> 
> beforeEach(() => {
>   mock = new MockAdapter(axios)
>   store = mockStore({})
> })
> 
> afterEach(() => {
>   mock.reset()
> })
> ```

That's work. thank you

**Comment by carlosjcuevasm** [comment]
> FYI, with Jest i had it working like this:
> 
> ```
> let mock
> let store
> 
> beforeEach(() => {
>   mock = new MockAdapter(axios)
>   store = mockStore({})
> })
> 
> afterEach(() => {
>   mock.reset()
> })
> ```

Indeed, this and [also this](https://github.com/ctimmerm/axios-mock-adapter/issues/34#issuecomment-280481935) which is a response above worked for me. But I'm missing the why. Why if `const mock = new mockAdapter` is done  outside the `describe()` scope  it behaves unexpectedly? Shouldnt `mock.reset()` and or `mock.restore` deal with reseting things around instead of resorting to instantiating again?

**Comment by ctimmerm** [comment]
> Indeed, this and [also this](https://github.com/ctimmerm/axios-mock-adapter/issues/34#issuecomment-280481935) which is a response above worked for me. But I'm missing the why. Why if `const mock = new mockAdapter` is done outside the `describe()` scope it behaves unexpectedly? Shouldnt `mock.reset()` and or `mock.restore` deal with reseting things around instead of resorting to instantiating again?

This is more about how JavaScript and the test library work. If you add some `console.log` statements to your code, you'll understand why it can't work.

**Comment by anicioalexandre** [comment]
Just mentioning this issue [here](https://github.com/TanStack/query/discussions/1441) because I initially thought I had problems with my Axios mock adapter. However, the actual issue was with my query client's cache persisting between test runs
