### ISSUE TITLE
Use Promise in mocked data

### ISSUE THREAD

**Issue by fdrobidoux** [ctimmerm/axios-mock-adapter#350]
I made the mistake of doing this, and it cost me a bunch of time :

```ts
mockAxiosAdapter.onGet("/groups")
    .replyOnce(200, Promise.resolve(groups));
```

Could it be possible to resolve Promises in the `transformRequest(data)` function in `handle_request.js`?

Thanks!

**Comment by ali3nnn** [comment]
why you don't await the promises before and add to the mock just the returned data?

**Comment by marcbachmann** [comment]
Please use the function based `reply` or `replyOnce` in that case.
```
.replyOnce(async function () {
  return [200, await fetchGroups()]
});
```
