### ISSUE TITLE
axios-mock-adpater don't work with axios version 1.1.3

### ISSUE THREAD

**Issue by tonglid** [ctimmerm/axios-mock-adapter#353]
I create Project with Vite react-typescript. First I used Axios v1.1.3, and it doesn't work, but when I downgrade Axios to version 0.27.2 it works
![image](https://user-images.githubusercontent.com/88360095/203009430-a4a0a8f1-ff62-4427-9fc1-7808c98459fb.png)

**Comment by marcbachmann** [comment]
fixed in v1.21.3
