### ISSUE TITLE
axios-mock-adpater don't work with axios version 1.2.2 (latest release)

### ISSUE THREAD

**Issue by DeepakSharma04** [ctimmerm/axios-mock-adapter#355]
Please update the axios-mock-adpater with the latest release of axios happens.

**Comment by tonglid** [comment]
thank you

**Comment by ilyary** [comment]
@ctimmerm, any plans?

**Comment by marcbachmann** [comment]
This got fixed. Please use v1.21.4

**Comment by ghostspook** [comment]
Yes, updating to v1.21.4 worked like a charm
