### ISSUE TITLE
Support axios 1.x

### ISSUE THREAD

**Issue by EranNL** [ctimmerm/axios-mock-adapter#382]
Are there any plans to support axios 1.x? I get a huge list of incompatible types when using axios 1.x (or I am doing something wrong). 

![afbeelding](https://github.com/ctimmerm/axios-mock-adapter/assets/10157169/c3b8454a-6e4c-4bd7-8b6e-56aba558347c)

**Comment by evelynhathaway** [comment]
@Kenneth-Sills I am running into an identical issue to the one in this comment in another project https://github.com/softonic/axios-retry/issues/159#issuecomment-1809406232, which sounds similar to yours too.

I use `axios-mock-adapter` in Jest ESM to test files that import `axios` in ESM, but I think TypeScript is assuming `axios-mock-adapter` is using CJS to import `axios`.

I confirmed I have only have one deduped `axios@1.7.7` and one `axios-mock-adapter@2.1.0` across the project.

**Comment by evelynhathaway** [comment]
@Kenneth-Sills I created #400 for my issue in case it sounds related to yours
