### ISSUE TITLE
Vue: Argument of type AxiosStatic is not assignable to parameter of type AxiosInstance

### ISSUE THREAD

**Issue by hc-advokate** [ctimmerm/axios-mock-adapter#397]
"axios": "^1.7.7",
"axios-mock-adapter": "^2.0.0",

The axios version type is AxiosStatic, not AxiosInstance

**Comment by besotti** [comment]
I don't think this is an issue with the package; you probably just have a different version of Axios installed (or maybe two different versions within your monorepo?).

This setup works:
```
import axios from 'axios';
import AxiosMockAdapter from 'axios-mock-adapter';

const axiosMock = new AxiosMockAdapter(axios);
```

Tested with axios@1.7.7 and axios-mock-adapter@2.1.0.
