### ISSUE TITLE
Ability to switch mocking `on` and `off`

### ISSUE THREAD

**Issue by exnihilo-creatio** [ctimmerm/axios-mock-adapter#43]
I would be nice to have the ability to turn mocking `on` during development. The library currently has the method `reset`, which removes the handlers, and `restore` which removes mocking from axios. However, there is currently no possiblity to stop mocking, remember the added handlers and start mocking again. Think the opposite of `restore`, but on an already initialized adapter.

Or it's already possible and I can't figure out why.

**Comment by ctimmerm** [comment]
All that axios-mock-adapter does is setting an adapter for the axios instance that you pass to it.
There's no built in support for toggling the mock adapter on and off, but it's pretty easy to achieve anyway:

```js
var mock = new MockAdapter(axios);

// Save a reference to the mock adapter so that we can later reuse it
var mockAdapter = axios.defaults.adapter;

// Removing mocking behavior
mock.restore();

// Add mocking behavior again
axios.defaults.adapter = mockAdapter;
```

**Comment by exnihilo-creatio** [comment]
Indeed, it is easy to achieve, I just thought maybe having a built in support might be helpful, since its not a lot of code and won't have any effect on existing code. It's a nice to have kinda feature.

**Comment by franciscop-invast** [comment]
This would be as trivial to do if there is an option or if there's not:

```js
if (process.env.NODE_ENV === 'development') {
  // Mocking code here
}
```

If it was as an option it'd be basically the same, let's say the option was called `active`:

```js
const mock = new MockAdapter(axios, {
  active: process.env.NODE_ENV === 'development'
});
```

So IMHO it doesn't make sense to implement it.

**Comment by xiaoyouyu** [comment]
> All that axios-mock-adapter does is setting an adapter for the axios instance that you pass to it.
> There's no built in support for toggling the mock adapter on and off, but it's pretty easy to achieve anyway:
> 
> ```js
> var mock = new MockAdapter(axios);
> 
> // Save a reference to the mock adapter so that we can later reuse it
> var mockAdapter = axios.defaults.adapter;
> 
> // Removing mocking behavior
> mock.restore();
> 
> // Add mocking behavior again
> axios.defaults.adapter = mockAdapter;
> ```

very good
