### ISSUE TITLE
Why no send request?

### ISSUE THREAD

**Issue by 953133667** [ctimmerm/axios-mock-adapter#49]
I used axios-mock-adapter mock the request.if i need send a request (no mock),for example:
```
axios.get(`/menus/getMenus`, {params: params})
//This request i need no nock, (send true request).
```
Look the google chrome devtools:
![image](https://cloud.githubusercontent.com/assets/9947354/24950400/85c1d460-1fa3-11e7-8f4e-c20971b53db3.png)
------------------------------------

**Comment by ctimmerm** [comment]
By default, axios-mock-adapter will mock out every request.
If you want to let specific requests pass through to the network, you can do so using `passThrough`, e.g.:

```js
mock.onGet('/menus/getMenus').passThrough();
```

If you want to mock only a few requests and let everything else pass through, you can do:

```js
mock.onGet('/foo').reply(200);
mock.onGet('/bar').reply(200);
mock.onAny().passThrough();
```
