### ISSUE TITLE
NPM hasn't been updated

### ISSUE THREAD

**Issue by naifen00** [ctimmerm/axios-mock-adapter#52]
Such as the method 'networkError', 'timeout' , there is no

**Comment by eperinan** [comment]
I'm having the same issue :(

**Comment by alireza-ahmadi** [comment]
@ctimmerm I have the same issue, is there any problem with publishing the new version of the package into **npm**?

**Comment by axe312ger** [comment]
Yes pleeease! Need the network error feature.

@ctimmerm can you please invest the 5 minutes to do it? <3

**Comment by ctimmerm** [comment]
I'll do so today.

**Comment by alireza-ahmadi** [comment]
@ctimmerm Thanks 🙏

**Comment by peterox** [comment]
Hi @ctimmerm . Still waiting on NPM deploy :-)

**Comment by shmidtkirill** [comment]
Hi,@ctimmerm ! It would be really great to have the new release with #46 .

**Comment by axe312ger** [comment]
And b7bbf3575266cd9cbdedb701c6b780cb3fbcf0d1 🙈

**Comment by ctimmerm** [comment]
Finally! Sorry for the delay, I was busy with other stuff.

**Comment by axe312ger** [comment]
thank you so @ctimmerm
