### ISSUE TITLE
Ability to define baseUrl

### ISSUE THREAD

**Issue by danielo515** [ctimmerm/axios-mock-adapter#53]
Hello,

I am using axios-mock-adapter with big sucees. Thank you very much for it.
However, recently I'been forced to change my app so it can be served from a subdomain.
This forced me to edit all mockup definitions, adding a base path to all of them.
It would be ideally to be able to define a baseUrl like axios allows.

thanks and regards

**Comment by ctimmerm** [comment]
Can you give a code example of what your problem is?
If you set a baseURL on your axios instance, it should already be taken into account:
https://github.com/ctimmerm/axios-mock-adapter/blob/master/test/basics.spec.js#L200-L208

**Comment by danielo515** [comment]
Oh, so just by defining it on the axios instance is enough?
What about creating a new instance? Will it work too?

My current code is:

```js
 mock
        .onGet( basepath + '/api/login' ).replyOnce(() => [ 401, { autenticated: false }] )
        .onPost( basepath + '/api/login' ).reply( checkAuth )
        .onPost( basepath + '/api/licenses' )
        .replyOnce( response )
        .onPost( basepath + '/api/licenses' )
        .replyOnce( 200 )
        .onPost( basepath + '/api/licenses' )
        .reply( response )
```

I would prefer to do something like:

```js
This is the mocker function
export default (axios) => {
    axios = axios.create({baseUrl: 'http://example.com/' + basepath})
    const mock = new MockAdapter(axios, { delayResponse: 400 });
// ... etc
```

But I'm afraid it will not work because you inject interceptors at instance level, right?

**Comment by ctimmerm** [comment]
There should be no difference in functionality between the default axios instance and a custom instance. (Note that in your example it should be `baseURL`, not `baseUrl`.)

**Comment by danielo515** [comment]
The difference is that creating a new axios instance inside the mockup function will not intercept the requests from the "parent" instance.

However, I ended using relative paths both on axios and the mockup.

Regards
