### ISSUE TITLE
onDelete() request

### ISSUE THREAD

**Issue by ximomompo** [ctimmerm/axios-mock-adapter#55]
Is there any reason why no exists this option? 

Thanks

**Comment by ctimmerm** [comment]
`onDelete` exists, can you clarify what you mean?

**Comment by bobmacneal** [comment]
onDelete returns 404 when passed a valid url. Is there documentation for mocking onDelete?

**Comment by ctimmerm** [comment]
@bobmacneal could you give an example of what you're trying to do?

**Comment by alainlecluse** [comment]
Had the same problem. Wrote a short test to prove it.
But test code outside of my project worked like a charm. The problem was my project. 

Test case that i used to prove its working:
```
var axios = require('axios');
var MockAdapter = require('axios-mock-adapter');

// This sets the mock adapter on the default instance
var mock = new MockAdapter(axios);
mock.onDelete('/example').reply(200);

var axiosInstance = axios.create();
axiosInstance.delete('/example')
    .then(function (response) {
        // handle success
        console.log(response); // results a 200 in my testcase
    })
    .catch(function (error) {
        // handle error
        console.error(error);
    });
```
