### ISSUE TITLE
Can Not Mocking a request with a specific request body/data by POST

### ISSUE THREAD

**Issue by woodygithub** [ctimmerm/axios-mock-adapter#56]
Can Not Mocking a request with a specific request body/data by POST
like this:
```
mock.onPost('/product', { id: 4, name: 'foo' }).reply(204);
```

**Comment by Olivier-Daire** [comment]
Looks like it was already asked months ago, for anyone looking for a workaround, you can pass a function to `reply`, see #10

**Comment by joebowbeer** [comment]
This can be closed?
