### ISSUE TITLE
Axios.create is not a function

### ISSUE THREAD

**Issue by dhaniboy09** [ctimmerm/axios-mock-adapter#58]
Hi @ctimmerm,

I'm having an "axios.create() is not a function error" when i try to use axios-mock-adapter. Here's the implementation.
`        

          import axios from 'axios';
          import MockAdapter from 'axios-mock-adapter';

          let mock = new MockAdapter(axios);
           mock.onGet('https://myapi.org/v1/', { params: { param1: 'holiday', sortBy:'top' } }).reply(200, {
			  	data: [{
					     author: "Vivian Michaels",
					}]
                                  });

          axios.get('https://myapi.org/v1/', { params: { param1: 'holiday', sortBy:'top' } })
			  .then(function(response) {
			    console.log(response.data);
			 });`
I'm doing exactly as the documentation says but then i get the error:   TypeError: axios.create is not a function. Any help is appreciated.

**Comment by axe312ger** [comment]
we had kind of the same error cus another test did overwrite axios.create with a stub which got not correctly reset.

**Comment by yzzhuo** [comment]
In my test target code I use "Axios.create(my_config)", and I get the same error: TypeError: axios.create is not a function.How can I test Axios.create like I use Axios in mockAdapter?

**Comment by MFry** [comment]
Does this library work? This seems to be an issue immediately after import.

**Comment by Gecko222** [comment]
In utils.js we have
```
var axios = require('axios');
```
console.log(axios)
```
{ default: 
         { get: [Function: get],
           create: [Function: create],
           defaults: { adapter: {} } 
} }
```

**Comment by ctimmerm** [comment]
@Gecko222 can you describe what your build system looks like?

**Comment by Gecko222** [comment]
Thanks for very fast respone, but i solved problem. i had stub it by jest mock elsewere.

**Comment by Gecko222** [comment]
@StanSarr 
im just mocking it via jest mock, i have created file `axios.js` in `__mocks__` folder and jest mock it automatically, then you can import axios in you tests and spy on it or make another mock implementation to test different responses.

```js
const axios = {
  get: jest.fn(() => Promise.resolve({ data: {} })),
  create: () => axios,
  defaults: {
    adapter: {},
  },
};

export default axios;
```

**Comment by belandry** [comment]
@Gecko222 
Thanks a lot !

**Comment by twilco** [comment]
This is still a problem for me :/

**Comment by shahzadcacf** [comment]
This library is useless without create instance.

**Comment by kilgarenone** [comment]
Hi @shahzadcacf , as mentioned in my last comment above, you don't really need this library. I also write about it [here](https://medium.com/@kilgarenone/use-jest-to-test-redux-async-action-creator-with-axios-in-a-create-react-app-app-d9c9b52eba5e) ..

**Comment by innocentamadi** [comment]
Adding this here since it's the first hit on google to the question.

With jest, you can explicitly unmock, then call this library.

```
jest.unmock('axios');
import axios from 'axios';
import MockAdapter from 'axios-mock-adapter';
...
```

This library gives nice, flexible apis when working with external requests. However it doesn't globally prevent your app from making external calls that can be triggered by a test in a different component.

So I found both using this library and doing a manual mock in the `__mocks__` folder equally helpful.

**Comment by r3wt** [comment]
Following up on Oscar's answer above, if you need to mock an instance created with `axios.create()` this seems to be working for me:

```
// easier to merge objects
const _ = require('lodash');

// cannot require axios, otherwise it recursively mocks
const axios = jest.requireActual('axios');
jest.unmock('axios');

const MockAdapter = require('axios-mock-adapter');
const mockAxios = new MockAdapter(axios);

// nothing important seems to be overwritten
module.exports = _.assignIn(axios, mockAxios, { create:(options)=>axios });// override create to return the mocked axios default instance.
```
