### ISSUE TITLE
Support cancellation

### ISSUE THREAD

**Issue by jacobdam** [ctimmerm/axios-mock-adapter#59]
Axios supports cancel a request with `config.cancelToken`. Its adapters have code to handle cancellation also. Can we add this ability to this library? https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L211

**Comment by ctimmerm** [comment]
Are you sure this does not work yet? I've added a test for it here: https://github.com/ctimmerm/axios-mock-adapter/blob/master/test/cancelation.spec.js

**Comment by FriOne** [comment]
@ctimmerm it does work for GET, but doesn't for POST

**Comment by cburgmer** [comment]
We were looking for the mock adapter to follow axios handling of cancelToken, i.e. throwing a request error if the cancelToken was cancelled. It seems this is not implemented here, however it works for us using `jest-mock-axios`: https://github.com/knee-cola/jest-mock-axios/blob/cf600ca3008791f15cc8705ecd5551188bec8663/lib/mock-axios.ts#L34.
