### ISSUE TITLE
Cannot set property 'handlers' of undefined

### ISSUE THREAD

**Issue by jper92** [ctimmerm/axios-mock-adapter#65]
Hi, I don't know what I'm doing wrong but every time I try to mock axios it raises this exception:
 TypeError: Cannot set property 'handlers' of undefined
      at reset (node_modules/axios-mock-adapter/src/index.js:23:17)
      at MockAdapter (node_modules/axios-mock-adapter/src/index.js:31:9)

Digging into the source code I can see that it's happening when creating a new mock, my code is like this:

```
import Axios from 'axios';
import mockAdapter from 'axios-mock-adapter';
...
const httpMock = mockAdapter(Axios); // here it raises the exception
httpMock.onGet('/providers').reply(200, ['Provider1', 'Provider2', 'Provider3']);

```

Thanks in advance

**Comment by ctimmerm** [comment]
You're missing the `new` keyword when creating the mock adapter.
