### ISSUE TITLE
Query params not handled properly

### ISSUE THREAD

**Issue by kamronbatman** [ctimmerm/axios-mock-adapter#67]
Looks like the mock adapter is not mutating the config by changing "/path/here?param1=value" to include:
```javascript
params: {
  param1: value
}
```

I came up with a workaround, but it is kind of sloppy. Importing the `url` module and doing this on many calls:

```javascript
.......
mockAdapter.onGet(/\/path\/here\/?(|\?.*)).reply((config) => {
const parsedUrl = url.parse(url.resolve(config.baseURL, config.url), true, true);
config.params = parsedUrl.query;
.......
```

**Comment by Nudelsieb** [comment]
Same here. Seems to be the same as #82.

My workaround was to use the params object in the original request like follows:

Instead of 
```
const url = '/api?param1=x&param2=y';
axios.get(url);
```
you write ...
```
const url = '/api';
axios.get(url, 
{
   params: {
      param1: 'x',
      param2: 'y'
   }
});
```

```
mock.onGet('/api, {
   params: {
      param1: 'x',
      param2: 'y'
   }
}).reply(200, 'myData');
```

This seems to be a quite crucial bug harming the main purpose of the library, especially since this behaviour is not documented.

**Comment by kamronbatman** [comment]
@Nudelsieb, I didn't want to take the assumption that others would know to avoid params in the url string. :/

**Comment by ctimmerm** [comment]
Same as #138
