### ISSUE TITLE
Intercepted HTTP method should be case insensitive

### ISSUE THREAD

**Issue by davidturissini** [ctimmerm/axios-mock-adapter#7]
Repro:

```js

import axios from 'axios';
import MockAdapter from 'axios-mock-adapter'

const mock = new MockAdapter(axios);

mock.onPost('/myurl').reply(200, {});

axios('/myurl', { method: 'POST' })

```

Expected: interceptor to work properly
Actual: 
```
TypeError: Cannot read property 'find' of undefined
```

---------

Culprit appears to be index.js line 4. If I change the http method to `post` instead of `POST` everything works as expected

**Comment by ctimmerm** [comment]
This has been fixed in the newest release: https://github.com/ctimmerm/axios-mock-adapter/releases/tag/v1.3.1
