### ISSUE TITLE
No support for Axios Request method aliases

### ISSUE THREAD

**Issue by StarpTech** [ctimmerm/axios-mock-adapter#71]
I saw that the `findHandler` does not handle the request options as object https://github.com/ctimmerm/axios-mock-adapter/blob/817ccd01cf22839e5611f466c759ab5b1292ae83/src/utils.js#L25

that the cause why this doesn't works

```js
 mock.onGet('/foo').reply(200, {
      foo: 'bar'
    });

    return instance.get({  url: '/foo'  }).then(function(response) {
      expect(response.status).to.equal(200);
      expect(response.data.foo).to.equal('bar');
    });
```

Here the `opt` is not handled as object

https://github.com/ctimmerm/axios-mock-adapter/blob/817ccd01cf22839e5611f466c759ab5b1292ae83/src/handle_request.js#L20

**Comment by StarpTech** [comment]
Its no issue it seems that only the `axios.verb(url, config)` but not `axios.get(url[, config])`

**Comment by ctimmerm** [comment]
I'm not sure what the problem is, `instance.get({  url: '/foo'  })` does not look like a valid call.

**Comment by StarpTech** [comment]
Its a valid call according to the axios spec but its not supported by axios-mock this is what the issue about.

**Comment by ctimmerm** [comment]
If you use a request method alias, the first argument needs to be a string: https://github.com/mzabriskie/axios/blob/2b8562694ec4322392cb0cf0d27fe69bd290fcb2/lib/core/Axios.js#L57-L77

**Comment by StarpTech** [comment]
Crazy I could swear it worked but that's the prove. thanks!
