### ISSUE TITLE
I think you `params` spell error.

### ISSUE THREAD

**Issue by tstrilogy** [ctimmerm/axios-mock-adapter#72]
![image](https://user-images.githubusercontent.com/22249411/29346932-649a9980-827b-11e7-8bee-b7fa56bba8be.png)

![image](https://user-images.githubusercontent.com/22249411/29346973-a13c08ec-827b-11e7-875c-b3fad2fa41bd.png)

so , we can't recive the `params`

**Comment by ctimmerm** [comment]
The `parmas` key is not coming from axios-mock-adapter.
