### ISSUE TITLE
Mocks with body data aren't matching

### ISSUE THREAD

**Issue by Scaalees** [ctimmerm/axios-mock-adapter#73]
When setting a mock:

```javascript
    mock.onPost('/example', {
        foo: 'bar'
    }).reply(200, mockResponseData);
```

And running the request:

```javascript
http.put('/umbraco/api/basketApi/updateBasketItemQuantity', {
    foo: 'bar'
});
```

They never get matched. I've discovered that in `utils.js`, `isBodyMatching()`, the body is passed through as `foo=bar`, whereas the `requiredBody` is still an object

```javascript
{
    foo: 'bar'
}
```

This means that the first parameter is never able to be parsed as JSON, and the requests never match.

axios-mock-adapter: `1.9.0`
axios: `0.16.2`

---

Update: A quick workaround is to do:

```diff
  var parsedBody;
  try {
    parsedBody = JSON.parse(body);
- } catch (e) {}
+ } catch (e) { parsedBody = body; }
```

in the `isBodyMatching` function, and define the mock as

```javascript
    mock.onPost('/example', 'foo=bar').reply(200, mockResponseData);
```

However this isn't very scalable.

**Comment by ctimmerm** [comment]
There's a test that verifies that this works correctly: https://github.com/ctimmerm/axios-mock-adapter/blob/master/test/basics.spec.js#L143-L151

Can you think of anything that's different in your setup that would make it fail?

**Comment by SteveEdson** [comment]
I've been able to replicate this but with `transformRequests` on the axios instance. I think that would be causing the problem.

I'm not sure what the solution here would be, could the mock adapter do the comparison before the transforms have happened? Alternatively, could the mocks also be transformed and then that is used for the comparison?

**Comment by mrchief** [comment]
#64 talks about the same thing and I'm currently facing the same issue. Passing a body fails the test. I don't know how the unit test is working but the fact that many of us are facing the same issue does point out that there _is_ an issue at least.

**Comment by mrchief** [comment]
I found 2 more issues about the same (#56, #10) but upon deeper inspection, it turns out to be a user error.  In my case, I was (accidentally) wrapping up the data in another object:

```
    const data = {
      ...
      , username
      , password
    }

    mock.onPost('http://test.me/hello', { data })
```

Changing it to `mock.onPost('http://test.me/hello', { ...data })` or `mock.onPost('http://test.me/hello', data)` fixed it for me. Not sure if others are having same/similar type of issues?
