### ISSUE TITLE
cannot use baseURL in request config

### ISSUE THREAD

**Issue by erwin16** [ctimmerm/axios-mock-adapter#74]
I cannot use axios.create, but I can use http from 'axios'

**api/index.js**
	const config = {
	  timeout: 1000
	}

	export default {
	  fetchShoppingLists: () => {
	    return http.get('http://localhost:3000/shoppinglists', config)
	      .catch(error => {
	        throw error
	      })
	  }
	}

and in
 **test.spec.js**

   import axios from 'axios'
   import MockAdapter from 'axios-mock-adapter'
   mockAdapter = new MockAdapter(axios)

    mockAdapter.onGet('http://localhost:3000/shoppinglists').reply(() => {
      return new Promise((resolve, reject) => {
        ...
	  }
    })

when  I set baseURL in config, it's executing correctly , 
but executing unit test  mockAdapter.onGet is failing ( see error below )

    const config = {
      baseURL: 'http://localhost:3000/',  
      timeout: 1000
    }

the  request raises an error... Error: Request failed with status code 404

    return http.get('shoppinglists', config)

failing
     Error: Request failed with status code 404
    at createErrorResponse (webpack:///~/axios-mock-adapter/src/utils.js:108:0 <- index.js:16849:15)
    at Object.settle (webpack:///~/axios-mock-adapter/src/utils.js:88:0 <- index.js:16829:16)
    at handleRequest (webpack:///~/axios-mock-adapter/src/handle_request.js:57:0 <- index.js:16608:11)
    at webpack:///~/axios-mock-adapter/src/index.js:16:0 <- index.js:16638:9
    at Promise (<anonymous>)
    at MockAdapter.<anonymous> (webpack:///~/axios-mock-adapter/src/index.js:15:0 <- index.js:16637:14)
    at dispatchRequest (webpack:///~/axios/lib/core/dispatchRequest.js:52:0 <- index.js:17199:10)
    at <anonymous>

**Comment by DarynHolmes** [comment]
With regards to `http.get('shoppinglists', config)`

Is `http` and instance of `axios`?

Also, the examples on the readme don't return a promise. So it might be incorrect to use 
```
return new Promise((resolve, reject) => {
```

**Comment by sparecycles** [comment]
It looks like there's some problematic code here, which *removes* an `baseURL.length` amount from the start of the url (when the `baseURL` matches the beginning of the `url`).
https://github.com/ctimmerm/axios-mock-adapter/blob/af547047408c8c969b6613ca27f0d24b2b924ea9/src/handle_request.js#L15-L17

The `config.url` should instead be "combined" (appended!) to the `config.baseURL` (see axios code [here](
https://github.com/axios/axios/blob/2b8562694ec4322392cb0cf0d27fe69bd290fcb2/lib/core/dispatchRequest.js#L29-L31) and [here](https://github.com/axios/axios/blob/fe7d09bb08fa1c0e414956b7fc760c80459b0a43/lib/helpers/combineURLs.js)).
