### ISSUE TITLE
The usage reason of axios-mock-adapter

### ISSUE THREAD

**Issue by burakuluu** [ctimmerm/axios-mock-adapter#79]
I'm a beginner to test axios calls and started using axios-mock-adapter but I don't get why we use axios-mock-adapter.

`mock.onPost('/api').reply(200, userData, headers);`

In this code snippet, does the request really go to the server or is this just a simulation?

Because if I give wrong credentials, it responses with 200 status as I identify it on '**reply**' to return 200.

So if I identify the response status, what is the reason to use it?
If it doesn't really go to server, it seems like this is useless.

Maybe I miss something I don't know because I'm new but someone should put the light on this issue on my mind.

Thanks

**Comment by erickponce** [comment]
When you use axios-mock-adapter, you are not testing your backend API, instead you are testing the code that uses the response of the API.

That's the meaning of the mock technique in this scenario.
