### ISSUE TITLE
Mock a post request with data and query params

### ISSUE THREAD

**Issue by DarynHolmes** [ctimmerm/axios-mock-adapter#88]
Firstly: Thanks for the great tool!

Now for my issue:

How can I mock a post request which checks both data and query params?

The production code looks like this:

```
const getReport = (userId, managerId, start, count, refresh) => {
  return axios.post(url(userId),
    {
      ManagerId: managerId
    }, {
      withCredentials: true,
      start,
      count,
      refresh
    }).then(extractData)
}
```

The tests I have

```
      mock.onPost(`http://localhost:3000/example/api/users/${userId}/reports/data`,
        {
          ManagerId: managerId
        }, {
          params: {
            withCredentials: true,
            start,
            count,
            refresh
          }
        }
      ).replyOnce(200, reportGenerator(start, count))
```

However the params don't seem to matter, I can leave them out, change them, the mock always returns the same data. If I change the body (managerId) then the mock does not return the data, which is what I expect.

How can I mock axios, so that the mocked data is only returned if URL matches, the query params match, and the data match?

Thanks

**Comment by bodinsamuel** [comment]
Much needed :)

**Comment by ctimmerm** [comment]
PR here: https://github.com/ctimmerm/axios-mock-adapter/pull/130
