### ISSUE TITLE
Sample project for axios-mock-adaptor

### ISSUE THREAD

**Issue by anunayasri** [ctimmerm/axios-mock-adapter#95]
Is there a sample project that uses `react`, `axios` and `axios-mock-adaptor` ? I want to check the folder the project structure and the best practices that can used to DRY code. I am not able to find a good sample project on the net.

**Comment by ctimmerm** [comment]
You can use axios-mock-adapter in a variety of ways, it's not even limited to testing alone. There's no recommended project structure.
