### ISSUE TITLE
Logging mocked requests

### ISSUE THREAD

**Issue by patric-eberle** [ctimmerm/axios-mock-adapter#97]
Is there a possibility to add a console log for every request handled by the mock-adapter?

I know, that I can define a function for `reply()`, but I want to keep those as simple as possible. I also have an `onAny()` to handle undefined mock routes. What I want to achieve is to print a console log for each request handled by the mock adapter so I can see what data was sent to which endpoint.

**Comment by skyiea** [comment]
It's surprising that such a mandatory feature is missing.

**Comment by aldarund** [comment]
+1

**Comment by JoshMcguigan** [comment]
I just made a pull request (#124) which saves every request which is handled by the mock. It doesn't log to the console (you'd have to request the history and then print to the console yourself) but I think it would solve your problem.

**Comment by JsonHunt** [comment]
You can define your own method like this:
var loggedGet = (url, response)=> {
    mock.onGet(url).reply((config)=> {
        console.log("Mock request", config)
        console.log("Mock response", response)
        return response
    })
}
You would then call it instead of original mock.onGet:
loggedGet(/permissions/, [200,permissions])

**Comment by alexanderkjeldaas** [comment]
@JsonHunt the main use-case for this is to have a quick&easy way of discovering the urls to mock.  Your solution doesn't help for the use-case.

**Comment by patric-eberle** [comment]
We eventually used interceptors to create a console log for each request and response:

```js
const clone = (data) => JSON.parse(JSON.stringify(data));
  const exclude = [
    /assets\//,
  ];

axios.interceptors.request.use((config) => {
    if (!exclude.find(pattern => pattern.test(config.url))) {
      console.groupCollapsed(`=> ${config.method.toUpperCase()} ${config.url}`);
      console.dir(clone(config));
      console.groupEnd();
    }

    return config;
  });

  axios.interceptors.response.use((response) => {
    if (!exclude.find(pattern => pattern.test(response.config.url))) {
      console.groupCollapsed(`<= ${response.config.method.toUpperCase()} ${response.config.url}`);
      console.dir(clone(response));
      console.groupEnd();
    }

    return response;
  });
```
