### ISSUE TITLE
Aggregate Mocks in one file and export it

### ISSUE THREAD

**Issue by Piero87** [ctimmerm/axios-mock-adapter#99]
Hi,
I'm trying to do this:

mocks.js
```

import axios from 'axios';
import MockAdapter from 'axios-mock-adapter';

let instance = axios.create({
    baseURL: 'https://some-domain.com/api/',
    timeout: 1000,
    headers: {'X-Custom-Header': 'foobar'}
});

let mock = new MockAdapter(instance);
mock.onGet('/users').reply(200, {
    users: [
        { id: 1, name: 'John Smith' }
    ]
});

export {instance}
```

main.js

```
import instance from './mock'

instance.get('/users')
  .then(function(response) {
    console.log(response.data);
  });
```

So aggregate more Mock in one file and then use it wherever i want, but I get this error:

Uncaught TypeError: Cannot read property 'get' of undefined

Anyone can help me? what i miss?

**Comment by ctimmerm** [comment]
The error is telling you that `instance` in the second file is `undefined`. This is because you're exporting `instance` as a named export in the first file, and you're importing the default import in the second file.
